#include "gterm.h"
#include <stdio.h>

void printToken(int token) {
	//gterm base=eps-1;
	//token -= base;
	switch(token)
	{
		case 52: printf("TK_ASSIGNOP ");
				break;
		case 53: printf("TK_COMMENT ");
				break;
		case 54: printf("TK_FIELDID ");
				break;
		case 55: printf("TK_ID ");
				break;
		case 56: printf("TK_NUM ");
				break;
		case 57: printf("TK_RNUM ");
				break;
		case 58: printf("TK_FUNID ");
				break;
		case 59: printf("TK_WITH ");
				break;
		case 60: printf("TK_PARAMETERS ");
				break;
		case 61: printf("TK_END ");
				break;
		case 62: printf("TK_WHILE ");
				break;
		case 63: printf("TK_TYPE ");
				break;
		case 64: printf("TK_MAIN ");
				break;
		case 65: printf("TK_GLOBAL ");
				break;
		case 66: printf("TK_PARAMETER ");
				break;
		case 67: printf("TK_LIST ");
				break;
		case 68: printf("TK_SQL ");
				break;
		case 69: printf("TK_SQR ");
				break;
		case 70: printf("TK_INPUT ");
				break;
		case 71: printf("TK_OUTPUT ");
				break;
		case 72: printf("TK_INT ");
				break;
		case 73: printf("TK_REAL ");
				break;
		case 74: printf("TK_COMMA ");
				break;
		case 75: printf("TK_SEM ");
				break;
		case 76: printf("TK_COLON ");
				break;
		case 77: printf("TK_DOT ");
				break;
		case 78: printf("TK_ENDWHILE ");
				break;
		case 79: printf("TK_OP ");
				break;
		case 80: printf("TK_CL ");
				break;
		case 81: printf("TK_IF ");
				break;
		case 82: printf("TK_THEN ");
				break;
		case 83: printf("TK_ENDIF ");
				break;
		case 84: printf("TK_READ ");
				break;
		case 85: printf("TK_WRITE ");
				break;
		case 86: printf("TK_RETURN ");
				break;
		case 87: printf("TK_PLUS ");
				break;
		case 88: printf("TK_MINUS ");
				break;
		case 89: printf("TK_MUL ");
				break;
		case 90: printf("TK_DIV ");
				break;
		case 91: printf("TK_CALL ");
				break;
		case 92: printf("TK_RECORD ");
				break;
		case 93: printf("TK_ENDRECORD ");
				break;
		case 94: printf("TK_ELSE ");
				break;
		case 95: printf("TK_AND ");
				break;
		case 96: printf("TK_OR ");
				break;
		case 97: printf("TK_NOT ");
				break;
		case 98: printf("TK_LT ");
				break;
		case 99: printf("TK_LE ");
				break;
		case 100: printf("TK_AS ");
				break;
		case 101: printf("TK_EQ ");
				break;
		case 102: printf("TK_GT ");
				break;
		case 103: printf("TK_GE ");
				break;
		case 104: printf("TK_NE ");
				break;
		case 107: printf("TK_RUID");
				break;
	}
}
